spring:
  # JPA 설정
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: '1000'
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      database: mysql
      ddl-auto: none
    show-sql: 'true'
  # multipart - 파일 업로드
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  # DB
  datasource:
    password: Ssafy123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ssafy
    url: jdbc:mysql://localhost:3306/flower_db?characterEncoding=UTF-8&serverTimezone=UTC
  # Oauth - 소셜로그인
  profiles:
    include: auth
  # 경로매칭
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# 포트
server:
  port: '8080'
